version: '3.3'
services:
  mysql:
    container_name: db
    image: docker.io/mysql:8.0
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  backend:
    container_name: backend
    image: quay.io/chisanuchakim/oasip-sy-5-backend
    restart: on-failure
    depends_on:
      - mysql

  reverse_proxy:
    image: nginx:1.20.2-alpine
    container_name: reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl/ip21sy5.crt:/etc/nginx/ssl/ip21sy5.crt:ro
      # - ./ssl/ip21sy5.key:/etc/nginx/ssl/ip21sy5.key:ro
      - ../ssl/:/etc/nginx/ssl:ro
    depends_on:
      - mysql
      - backend

  frontend:
    image: quay.io/chisanuchakim/oasip-sy-5-fontend
    container_name: frontend
    depends_on:
      - mysql
      - backend
      - reverse_proxy
