version: '3.3'
services:
  mysql:
    container_name: db
    image: docker.io/mysql:8.0
    restart: always
    ports:
      -3306:3306
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  backend:
    container_name: backend
    image: quay.io/chisanuchakim/oasip-sy-5-backend
    restart: on-failure
    depends_on:
      - mysql

  reverse_proxy:
    image: nginx:1.20.2-alpine
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - backend
  frontend:
    image: quay.io/chisanuchakim/oasip-sy-5-fontend
    container_name: frontend
    depends_on:
      - mysql
      - backend
      - reverse_proxy    
      

