-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 11:28:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Time-Up
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Time-Up
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Time-Up` DEFAULT CHARACTER SET utf8 ;
USE `Time-Up` ;

-- -----------------------------------------------------
-- Table `Time-Up`.`event Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Time-Up`.`event Category` ;

CREATE TABLE IF NOT EXISTS `Time-Up`.`event Category` (
  `idcategory` INT NOT NULL,
  `eventCategoeyName` VARCHAR(100) NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventCategoryDescription` VARCHAR(500) NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `eventCategoeyName_UNIQUE` (`eventCategoeyName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Time-Up`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Time-Up`.`booking` ;

CREATE TABLE IF NOT EXISTS `Time-Up`.`booking` (
  `idbooking` INT NOT NULL,
  `bookingName` VARCHAR(100) NOT NULL,
  `bookingEmail` VARCHAR(100) NOT NULL,
  `event Category_idcategory` INT NOT NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventNotes` VARCHAR(500) NULL,
  PRIMARY KEY (`idbooking`),
  INDEX `fk_booking_event Category_idx` (`event Category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_booking_event Category`
    FOREIGN KEY (`event Category_idcategory`)
    REFERENCES `Time-Up`.`event Category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
