name: timeup-runner

on:
  push:
    branches: [ devV2 ]
    
jobs:
  build:

    runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
#     - run: docker-compose rm -svf frontend backend reverse_proxy
#     - run: docker ps
#     - run: pwd
#     - run: docker image rmi quay.io/chisanuchakim/oasip-sy-5-backend  quay.io/chisanuchakim/oasip-sy-5-fontend frontend backend
    - run: cd /home/spadmin/OASIP-SY-5/actions-runner/_work/OASIP-SY-5/OASIP-SY-5
    - run: ls
    - run: docker build -t backend -f backend.Dockerfile .
    - run: docker tag backend quay.io/chisanuchakim/oasip-sy-5-backend
    - run: docker push quay.io/chisanuchakim/oasip-sy-5-backend
    - run: docker build -t frontend .
    - run: docker tag frontend quay.io/chisanuchakim/oasip-sy-5-fontend
    - run: docker push quay.io/chisanuchakim/oasip-sy-5-fontend
    - run: docker-compose up -d backend frontend reverse_proxy
